export {
	SidebarProvider,
	Sidebar,
	SidebarHeader,
	SidebarContent,
	SidebarFooter,
	SidebarNav,
	SidebarNavItem,
	SidebarGroup,
	SidebarGroupLabel,
	SidebarTrigger,
	SidebarInset,
	SidebarRail,
	useSidebar,
} from '@/components/ui/sidebar'
